name: Run Node App

on:
  push:
    branches: [ master ]

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run app.js
        run: node app.js
